server.port=9090
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Route requests to greet-service via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

logging.level.com.cognizant=debug
logging.level.org.springframework.cloud.gateway=debug
