# Loan Microservice runs on port 8081
# Different port to avoid conflict with Account service
server.port=8081
spring.application.name=loan-service
logging.level.com.cognizant=debug
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{25} - %msg%n
